apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: barnes-biz-wildcard
  namespace: gateway
spec:
  secretName: barnes-biz-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.barnes.biz"
    - "barnes.biz"
