---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgCvPXWRO6Vn9TCQjdpj3e4A9BYCWjvfZuFR06Qlw+fmOQhKO5vmWX3Oj5OsJDWRRWJDE0ZwO/fAKl6kzvkmSzOrB0PUJIsZTAkB9S0L+mbPu0OzIO5km4UM6fVszdIZzFGYRnbCTBF8a4hZ8/llPWFh6xmETxJcWH7vmkO16AT4AHm5iD3shsu6xvOpgS18mkhMJ3s/KH9Ni58myfoDAScI7UCnrMJYbWZtvOuLrD50Oib3g4cE6y2khlsknCv0hc2HGPcJmsimKchBwfPnMWj/cbTD1ZhBbrXYZ7xp9YjIG5Y/leom+Jl6M1zkGUoDirGMvJbFAw/kqiiDjnw69hBf8gxoh/9eGrK+x3ElO/AiW1Plu5KskwrJt5fFz2oTab2ycZMMkg4zPyke4hpmZsyeeozJ8D1+w9tTsQ6HvCt6JTZxeT7sKKOi4uqv7AAbTmTFFqEML+1/mtGlxm/xT9ylVZKflcEozOiprD/pzOIYAMnyVlzVeuXl0gdDFFogO7dG+vqreZY+g0OQC9neVoa0wqTPQBiXk9ogQvZ5VST7bhmvAQF9BfM4HpZnzBwusIY97onvaEc9L1Qc6CfGVXPF8x99TR/PSVBfNoKkOusA2EA1aNDk8OogV7BfjcUn6KoWJKES38CKTFskrtHe8TNa0MFEFUVaEhwlfBcHAx6g8A2iUVR4SM1h7zJc71RKBlND0+3VbcYX0kBdYmpd1GS+MWLWOA==
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgBPOXN7WskAb09VPV76IDcC9ML1BLtO5dVKmBRKKqPitpp+ObZiHmyjUxIYjSiQi8Lx6z02JKcX9ANM3rlhyxERmL5iAIZBT9zDBKlj35YGH+BYO/qBpbtl+cfW5+fmnWtwOIFxcnsrskRog9Jjq3CnuZhwmwys73ur0zOZ3HynBjzffwZ1d5F1ERmKxIgx5YOuKj8z/reLIBsJC76+2uVfaTkZsbP8aaupLyEaEJgXVrdau/2vm7K7M8mpe/kfuphEtfu7QGdainrPOCiG3uQCW6Q8ITPeTY3x/t85OYX+k3AfsCRwpX6KwLETfTw7cBR0PpXTuwZiSeWujSW7N9BVkPGyv8QDJll7NWtI/LBqHr3HbLBkFCNKS0H1FYS2vTasmX6IaQSd7VTe3ATtJm0oJ/3zDsoYhKuxMZK1zFpNq6R1aHQEKHWeRVwrE8ogB4z5YOzCaQYZgrH/ZZVbL4uISVh+GUIri5+dPjrNS/FjSrf5RP6bhHQA+rviU5RFs7yOpSb+Xa8MZAZS8aXUYs7mnwtGhf5GUAU1ghrwqb7zKx9378JgenVRZf3yDRmTGdzb5Jvy+1tfxKjPCpIrPP3ciJA6Enht/d1HHdj6SoQ1J/oE1dympKmMNcxrE6zVO/DM2HZK0pY2rUQMOpozMINjLXCPMtFrAXDbLOerZUtdZhP3oLDWmXk9hj3n32h4VMVFmMrzw5EiISFC3D+5iWubrCa5aQ==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
