---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgBNfeM2qtdjaSyxMQMDO/PEOEh9OXKdvRuXOrNMKgQpbjBJ0+/kQ/AelUuqjmT/s0LWoxti86bOZnR/rwX7v/+MlzxzXmsWJCLWAXy4Fg0QEAHpU5fLdvQ6CZl4RrWXZffbw2PmEIe3QpBQt/OE4Z75UvMqdsntx9890dby/QI9BITtge1HhOjF8vnCamC8AaE96IBYwsbcR1nrBlxOh3BAJVdHQMUzKoFntiU5ROwtaPXOW+jkAJ5/2IsWlp6fMYsbUm/RFCBhjSmBxFJx/4CY+BhmVsjRbZMIcgZtZFcKek0J8FjBeFdfV4auu2VVWlh0D3qR931+4dgPfZ/453cgeULjbY4n9lx4htHGYzzRsoM8a7vihcLUueXWWSoqjkQc75PVL92I4/VVioRbu2Nv56AnrdUWoUoQT7S8o0b7fhBk0elI4kd5btYKqxsz/JlSojHhFJXAaFb0P+rbGoaMWGTSfsF91DHhOBQjWLPBInw4a0cDcbI0l6C7mwFLv1rOfBDHvjOPxmS0PAI81OraOiCx/B1z2lI8jL2IMAikeafwSnXmxOMJr9pUuCHedKWQckuy/yOrhyCxDj9F0WGLi6B//FY9PKIe1Eih1/iI/FHtEQYrXrubhxIL66ZMmR6RP4vJ9S7bWLMldlZ9Cj67ygPqW2ZnrqrPctANAIowAM+VBFKnljYVZ12sx0+JMpIOP6SYHGYlJ/3w4/LTJys0QiD3+A==
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgCa2FpwGYpIw1nWJnMlV+juVTxF15Tg6OHStjB3nwTiGKmgNZ5UGTpjW0mNzjIzzWIoasQPKxWOxTYBkVWiN6Z77m46HC6yE76mk5EcJh0i6qD88koFSVNXOAM+D/pxqmiqS5NUVMzksC+4qUgmahmAN4JuyyD2HFTJW6yIpUCHYQk8pIdKHQllw0hL+JMiS34sHRvYA8iyicKspg3p/DGjqCHCC1mkBTUrrZviqQcfBRi/pVas8gZdiG1ulAuPWjaqRhiPsHuXZb/U/j4REknZFg7DFA+K9tSZHJgWm1kAUKsgvXw0IloPGa0NlTLZaeS+mWuqakzx6CfjYSUY4HCMHqsqKugWbQpLROpR/41KdipI4ArXwTtqf+A5Jh/DtBmADKPv1PieZRUkpRnVhCwYC2y5PgdCKfp9W8T8GnAMCIc4tlrXjBrlj+rb32PXbGWaf+tP5vreLOkqbZuVBLLE/p6r/3WYF0vTTjE95uRO3vtgikmsHRlJALA5lHDYBDAEXVzOg6Zun/5uKc5HCQ1jvtigiM2W2a8macXWrG2dEJHxo+YnVMjN68O+Czadv8gd57pU+beuDAFapMErPu1pojj3zCGXB2oZfGSLU8B1m6iEf8YKx3eAJGtSXmCEVMCRIHhNC9+nb7fj4O72nyrDXn5GoE05jotWjy5DnWUmJADonNTKmbCErpklwaRsElowmphC6vjuILhUjrOu7SUMM+QBsQ==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
