---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgAGxXBEajYzHtwSVtrFON8fTDYPsNfp5+EbTSStGu0WMvySrzskYLx8PMxuLOF5wCFE7jgeqaj3BMmhigivp4cGsJKUMXFxBGVEFFhJ64kvn7TMoW/IPpIrXERZWdn9NMrwDMyReHjVGuIanyepdLUpSYR+RuFk1BaYMHWzPhU3c6UjAixyR3YnhNx3nqXKFhYc4idQGIrczTBOTSBSXKfi4s1NJt+NNcpuddKf5sJFJk9oOCVIneCQm/FJhlv0hePrDX/S8djCNQSTXmTHGeQLPnVXZdMw4uBrJbW8LGD4pxA3EyVSNwAkIr4GFvHCbAH/pMoeVDTMyHERULlf9EV8QjJDjjeUqKJ6/jJy94JbTRSi6Xp6kKrg01rSO53PDtkdu7O0JVnKncvxCFZ7TXrqgy7d4iKgIwLSeyBvfpqNv5DZIuKZSYEKnGpDEUhVORYYEL6nQ28nP0O8pnHy5tPLz2B6PLwOHEt4AbuYa8kJJ2spWJgcrWQsUoxPWyHeqD7kZMjaCgFkPcbtRAJapxHX4F7CbdOCecR/PBkSEpJxdC8PrUZd+7OWPvTYM2qw2I4G+MnpeWcOSVMd8kYHo5/CoMaqtDr+fRvJuFNGlagYNtrl+RUWx/2WcZrVQbHDrmcu8zAJ4tw77r2JGQ+lccs/fq7v589Vw+rPjL98leDrIZSbGc7BjaBs3ARZ412exuXOb0CyJqz5gbC6OkqcWrdfNErrzg==
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAc+zNhMkqYpZu8vFFeIOzHxy10Ma2XLFCsCgGPZ9Q3oNfd1+OIdLNSJDtl5GS2U2Bq6F2NpMTSO9Mkc5G/nOG5voCIedBiyjv8mRkQSAXtUv+f4Hl/9JNXo5Y45ms5RhUZPgsWwN2kDTIJPlM5F7bqIR3mpX30nJ5FDSUyOtTzt1q/iKfeWiuEeUNm2pwlo2Mq5neGPZ1bh9fxm4DMIHwFmOnmgKANY9OH6yeEaoDM2wNeBt2Bwhsjn4psZ/K6fpCWVgrKRsuguRJHlIDx498uhMkilByHf3RUk7sCpinBtyjf7alkBG6osw7oEd3MmepUsSGOOaM7kTAjEH8z9pOzH1FbuvZFV80O7zKjF7+oYhTcUeZxhr1QXgCH6gGDRhmotdx/wysKFPdTwb0LmqLZqIPb36ZTN2jboftIT9Jw12Q/6uSWtOa72D/jfP8Ca6JZgBBhCEIzzPeI4FM97WBX4DjhRmmJYOhLiQiQ5K4HwmVcV3NsoAAhotsTDKWQUIL69fIFPH70Nakiybltx3X/0bPiSgqwxIaC8vCBoN1hTjeWcKuhVYbpQUrpC2hPGb5n3ozyVmZ50yDzL2cvo4MHr2OuGghsFo0lOmlgr5G/3IbjAXrihk56DI0s+MkoU866LEFC+FJ5XJiJawfLzpXxySt+Q5zpz18UT+AfSynFqMCAaAJwE5SjiChMx1mvLGu8Fa3utkLSS4PWInac06l0Sc1Muw==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
