---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    dex.authentik.clientID: AgCyAKyCMq3MA5DL7HngxLdPTpitpHVIhtZ3wf9QutXUlb+jd7E1Eau8exvqpwUEpQarXRzEoWn38C0QdmDnl60tpfGg/glebRpR5t1W0H/OW38I2cWP/xM3yKqhOrzk561GVEUpnByyK/w192FNXrbRuE5JTNplkfU43t00l4409IeCaJJSN37JzW9bwdLRyBqMmQR4mtvefyNYoZxwOuLYlJIXyfSW7Yg3+QwYcd2fM+3bdufpD1EF628lYrwgJe29LbdzZzmacvbAZbeIVQZx2EwSraQHrOScIiqwf2T7TaY6PjI4QRHpWb9O47b+u3o7+L8DTI3FnfIeqiBjjOPGL3cidWH6d1oHdLIxuoqUkg7bzrTI2Nd0Zq+BHE8jHfbFRsrhAlUVXOy2w79yakFNq+zgGZdvn7lvUnUEqk3wIr/C/ZGLqPEkPwOny6pHm5ATU/YwiQjKIbEiiyh/oLbgC+hHYVBDAEUaH9IzdrjQeoO1NwrhkzTFY6vURi/HAvdkWpDpTY2BA/gEzK3krRKyBZI8V/hNa9DVEtX483Dt9zeHq6OdNMpUHwhL3VkFnjhRyzqRvD+AupC1gFAP99IKHdRkn2AE9kA5lu7oT1LDIqy8k20Hy+8s8MPsiUro5ieOe3OLXPhFmU7kd7hpOMFjGSp2eBlPhWB4Eb2Ac4JjbbwiRtZR+nmgayMeYyjFNdIV/9kxh9xWrLQF2Wx48VJ6dLTijQ==
    dex.authentik.clientSecret: AgBCCnzNYQIhoMlG8xsyddKAAMEpTVP5OKg5Q0NYYoPVQUqCMnTlMjtMQ+nZNMpGX4ujd0+0KW84R3V7f/LP4DAdjxbPxGiqkPubUEqMGki1C+cXSdcag6enuJsSotETG4EIc3IQE/bTRDiyr4liIqMWIsSYjsBV0/TrzU6z/OfsZaP2kppnluTVMKXKEoH8eV7Cj+rAYsNrXZVGlNgB5gpKST0lrTyV6eZ3zHd4PTyhu1Odnv6YVTUigaB3Nyyr2U5dNWjcYtcM9cC1GOevn3Ddp2hK8HsSB5sHMKB4xLfB8ZSDrSISwNOngzFOS+KNAK5xgg9jmqpWDyWf4/Jlzt9LCT9ssysfNK72yieq4Hq5aHcfncwNVSHuWi0+GzFOGGhMyE2fs9B9Zoh3rtmRghZTP6RadwF2JO4sCnp/wbEvwCVhCUzblE886CL+ae4ebkbSvS6feHHzNBI3JbnJJpIoObUCO/2U0p4RLW2RNoN/IBWIxpp/ha/ax23VnWyUD0sij5tzXa2MbHy0HZRIP1uRb/VCL3NTMYcmfiasFC/bvStfc80HzLnNNpTfXEv9+qx6Sq75eVu3Az+QVxMNPLEWaxfwbR6P7qNFHPwbgSDnPHeJ64afSvcnnj2x6IXZIMj8wqtyDrpUotQniPBLFKCbTKBGTiUX4rkYS2Jf8XX1d12wFgP2IXWv0y8RipZEEAJu8G2xDN/2Uu3KU/D4YhhfP8aRmQ==
  template:
    metadata:
      name: argocd-oidc
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
