---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: barnes-biz
spec:
  encryptedData:
    TUNNEL_TOKEN: AgB/AtiTDm//sczrY+BH99WkplnZTZC/WBqfe94T9XCHUDI2qXwPfgRsmLjCspxIfA1KKPHxiJfAZsoNNOTRyYnznXVvRSXSuuHyqYEMWWcj/f668VaeY69s7YEhHd2GVOEXZn0rVt4Stack2e0Yt7nnXPyWa24SWsMnty9vcpAAW4b8dayzywyxxClcstCzpY2qCljX7BZyHq0T43ji6qdiOTOFC2jwCrwCfHZb2N2XkbPTOyY+CNWA1lVYUUeLVnmaxUsV4/rx/TmYDnsznPudTg5cH4YFjs44F5oTno917dBTFH0VeiMqIte1VJIMJOdf/4GioOHweNjMW943mBw8pVI0C7hg1C33t8cxwCDlTxeXmwvEX7E5iGIog/d6vU/XD36S1Mrbc3YLGkPUiqvs+YvacC6PNFtvlw3KrmUVnu8PAv5dsD7ZjlhpDXwF6EUwvzLbohuAn9xBoCRC2ZK/l0y6DDHWf+01O5a9CZJH07hqftg4zBo71i5E1bRW4NpN80GgeVsU9lBy35eveJKATXhHPpeovd1hgttvrlOgtzKiTmueBBy1Ht5KfT1WME/s8nNbOZ9//bqT4pjAk/D3UQada9bqCBlUayhpc4Uvuh5TPKWwQIzpRt9U4EazpaOC2Lt8EFhaTB+jUA/3XFpTGtC9j0DKWgiOdQeuisxlzSlb6ff8N96ngm0oqmQmwkVoTV0dz0KUkL2eWLCUzbaZntKnvbw1j1fe1WR3FK4FrfzzGLeSFEvb1DmIqnBDirRqXu/BmPcHEHCf9I9yFR0U+pVxr9HxhPquX7Q1WTAUs0Slsjt7HpzpTe11y7UZ8Dewr1l8ux06OXxBHSdpBkrfMJaoJIItYo7MPBMHRZ1Gs4BlDvhMD1nnd71uiA5RN9n14sZg7pdk51WrTvj5LSx+/qLHI1ilWhRIDZ6YQHmt3IHIYZgZw/ng
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: barnes-biz
