---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: barnes-biz
spec:
  encryptedData:
    SMTP_PASS: AgAcxaC/pvbEKVQ6dYakApzqDkn+a3t0fjiU30XOyid9F8+AofrTNNHJlo3KnNLOkbpEmmPxyCKhMbLy2MFUwEEDC6O8eRHxg4QOLMaQ5aS3edAqxicH2mKtgJ6ZDlsEaqP9d/x9Funnk74SlLuaisofNnJ7tBDjaZueA5gyEfq45McUUKH6EMB3VisHrP0GbOW3/orunTy6m84WQytdXyjomNfTMxmehPH1826Y4clrCLlxR9w1Wkx1wWB0C6v1I2CKB0M4tXqm7V+LfJpU2qYAvDjkdTa5VoVoBzq9cDldpNPGFsPYsPtXcmns2Wj9gBXf1Hu9LvFhuznQJb9ATLUhWr/BRblId/KTAsm3qFNGecRC88hte184lYrQQsTP/9QCgMq93kRde/bxHTN6d1hYp7XNP+NA/g4ihijMQcz7O/+TEmHGoWNDYC7h4yAT15FGl07kh1OMvtJ3+F8I4C8+untwefAjsrGYCrHp8X41Ws4hGs+GZUPRYiBTr7CURWSHFBqQJb4EkOHRl0dBxnygfIBK6VOUrlGAxksXsQ6ynTIPzB1mqGscnSivgxtah2Ev4D9d3jvvDeKr4JK5OQPECfx8ELkRDCBq1T9+rrR2FfDzpsCsltb/vyRW1MUbuZGBJXyBYA6O8gmoBfVNajR+WfN39mfCWZTbw4vtJsqwTbCrqsViBwaivq/gPvrMzKRLWUSq/yJ0WkUY6H6k1b7BGmpm
    SMTP_USER: AgAzBkDt1vsTBtL+zJMEd0skWm5sKmgo5oqpKWbWTfm66j1tJJ6kZWOQmoKTvX5EH3nYSOAW0mrdyJHOcYr62JF9zNNQrzxPc1h7KAaAPVLIODZlx4GKXcWiYkkZM08ndGDRUJkI7VlQkWrL7r+ykt0BY1QMt2WTHXd7xGdaPnh+00Eycfj13QgC23mREEXYhc4E//w5rqYGAUQmmENJGrCewaLZ4kSPW2Qix6po9whfBTHqgZDJCW5/Bnmmbz+oEgt9G85VpX/F48RlhfYvTAFAIBfcsW8OmWagSqwZppN+AkNhdBz7bWmS1PbKRq3NWY61/K+K2BlEJkZIgnLlU4NfXrxcH+p70n5u+0W1f/BO4Y0yCKBuaEWwGfVubM4BxeCcJGvjD+AO2KhONRJGYnFSOL1SvZwcJrx8k2X0etnndMhHOSXLRly77ihE6qxCe4/nYdxX9Q2rRcLMaLSY2Khv6oWUG62a6KQIeKdn8NN6Gijs5/wTFp3PU1+l3leYAn35cDwpVtzgl6qh0JYHHNgLScGQzaaEnpKvS7AStWlb42LxbjPpXLkHDBoOmdAMBSZzwV3WcN/ZWWDNNHTwN/kSBwm6dRRg1XLNX1WCQ9XFsdk+i9fmpxomrCPeF8cPK3BT3bteJAtysVy/BigCYGu9UI+dpj4blwjfcHbMikoAhgCSlaH/WEDWon7rxmEIYmD0wYh9P/iEAsLrAwMdJmK6XfKnad14gIPb+aHhTHnq
  template:
    metadata:
      name: smtp-credentials
      namespace: barnes-biz
