---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: barnes-biz
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCyFZW2+ROHwzU6V9vMJ+uXEtkfhN8gmXyWz0IdrqOJLkiZTI9xvoNv94b0s7f+KXv26hVLQvtYEoL82PBougrzrOa632SAg8zzivUJlA+SmNNdfRZgFmYci3qtDFPC/s0eknYEq2nexlshNpm+7/eKSs2VSQ0VhiwG7GmZpLddPuQVA6ucexpMBn0TuGKWFHkuBa2y5qLf3tssm0WLvRSkOEGSoJSPV1PMDe/1Koc62+SaxfVEUxE44AP/bTWWAQ8nXKC9+1ZVkKxXyu+KWnrH+3LIsFJ8W22gwL38ONRQOyJ0pyMoCulOxoEp7ZIIGMludrCb5DSnS/BQUDKVe2qLHLombf7d8a5VI2Yxor1KwIyhQchUr5LhdJQR0nVUTEJ/CWd6ZXw6LjMHTpkKH2v4fOa2OfcqFNSykxM8TZjqHvhSWqbiCEbPxSa8qli6IUt0kugCQmOJF6Xg9NuPa9hDFZe1cpV4c539wpFNfZD4sVY83w9a0qEYHL/6JlmoVCEGejwT4VO8XMYzdNgPMGt1HAgtc2QkbKNzr6m6PoUH+TdfoevMvxsG0+VynTxAneAoRDJMid6m7P3h4KVuIEPmzLGyMUhM0bDHQRgFcBdC4Hsf7ToqpuCwxIk2IqKR23V+44tZo1K4Oxjl/P7Ge0zkegGv696qjqOZEEYJz8nrAPK5CzdRzribVv7CYtrMd0LZfcsrGncvZavt0fVKEOgqYq1NtCWfF75JsfWFJxTkngQd5boq7TmBTNjZpHwbmV2pbQfrS3yVnnxoJzklfhiPY+kjgSgxpV3T7mrvQ/dgOZ8ktYsRTPmS/1FbbpA/QmOyrPZUcV9ho8meC32D5tiiRzDPjdO5D6S4S2iGgDMP9Pvy4NHnQ73v2RwCDQ/tuuLQQVKXp7/+gCda3ubG0CUtkQFTEGs8Cg3PgrwV6z2A5kpRVFzN2oee
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: barnes-biz
