---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-credentials
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgBFIh0bi3B4cfBIbICczBDZm84RNSSBK1JnU76Pv1ctoZIqBp6LZz4BqFgXV+rNMDd0AtCi1Ca1C+m/iiUKQkOBOpvOPTsiY7bTut6Dr/9Y0oQiIbq4U78X58Uh99NQYqt9eG36mMWNL7VJXPWyPyqoEF1LT2nBiOsZNcy0O4hYnhr7rCfh8vBi3z+SCwTT7vThgRDMAad29lOBruR2mDbDJHQT4UTODV3XI1NPhLCReAaxslMsKTS66AxoG/yBe0hmWTJQZwl/Wj0ucWGw2JSwkX4tG0/icpQftdBj/fhoSi0+9lvxGndpu3CL9Df3uQxRjjcigw8rr6qvyntdRd5w1qqeU3dyJBYv/3bkEvczll+xf9zEUVWhT9241gHSF3kuwO0sZjM7xwSZ/PaMKVr8jK6mUH4zfc3bRX9pgvU/HU6YgF2OL4Dn1sp4DwCU6+S621q6A6xbr2+AZjiS1FZoEwE+OjTASzI+X3xqWjg1dI80EnQ2AjAZKtArxKYSYOEGj1nIY7+0GuIf+FEjoyv4Mt3G2sJG/J5634+n+5luC4lEg6m0qjrGsEtyNTqO7MnTQzihVAMdGCku0SF2kAM1d3ZpFgww5vFEaY1FkJiI9oJW7eJVgU6wiC39YiR6grWbVPYASfEWU7gGs2cwR5TPE/UHxHL9B7HmTUOxmxzev97kku6D4OmI1hkuWY1Rn5gd7uvGDdWdfgDMvlHvaNyDtEh+Tw==
    DB_USERNAME: AgB6kfJe1Tl0MOpV5Mh4GpIFVtWtQ/CdI0QtQrCO9MpzwfDVCiEZFIRCFBJNMnGxsWesaDlcrLz1+gTWGbdnT/b7XeN0R89HR93MYrYdm9j0uBL6e1v39fz9h2gVq0VPrAaA4oEquaANkZMNYgMjSLRSArOHoyejFMFVqTqTZEsVQNSGsApJmW8Y9WG3RRj8q1gW6aq81lRPxkMShpz0ClU+qrq6YwrCeU7YukZzhX+ccRJ0QJz0/oCAWDnawjeONp//kzUfdRfO5f8m5SyqdOpDjYXrmGO126ysBzG34Qam/aoEbWeN9XloA4BFPAEZXMc4f0tymSJxh0kLx/LH+ZotGw0bUMjU2HKikTA7NNyfenqTi1L3MKDCppZOktBn5fVeOv36wXcaR2j1hSo6stC7icBejQR1jLpit0vaBXfgcPq7Q7zNrJhzS7lT0mAapyg80RCJMQXEWptOyavWKGA3uloRpqlPTgKqtNunt7jMQ9DRfBJKAD5qiU4eM0ux1Gn17OKr4fnU15z8Ue7HgItVpWmYxTnA9N1ICnhVFCnDABFCRvFtnqMQ4kvCG4Re4RPcJ5reBLYKErZizmHXzEvNArMZF+1KbRYzqOsozRko21Dd7s780ZTG7ykNgyH3exetCUjDfVnnE67OY2TcDdG+weVBd2bCQQfrgEdLHb309FXzPLTGdMCq+9uXrThX7/YrnTJOPoePknA/uNGvYjqk1CO1zQ==
  template:
    metadata:
      name: immich-postgres-credentials
      namespace: immich
