---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-credentials
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgAC2ANmosPilJMyiXkwYqxTiUxzLthAILBEMmAW9gzUxkSSi2aM4lvn/N4bIocmM2fUQQ8LnMfWa51HDiQvjZLevDj7d9RD3mgPgyEVlqfj75MYUHZMRbqFjCLIXW3CAGi1EeJvjm3mgkFEnkOaue5SUcJFEQYy7dK58WjYdFNrqd/KFI7ZaWMO+t84bE2pkbR+4m8uKPm5lIAhOZvRysgqjAkL2oZRrLr/H/wLXY0bYrYU9NGzfVuFUryTsyFrsqRXCBtVUxuJktYcsdrXkSvyeyMcwbXPAk0u3V6sN2fPo463sRwx3/v9RHRk4SPRcL++jzUzLrCyaOUsmn2MdhGvHaf/ZTLbs7ErzF690gbh7H0DstMVjeA4I06INN/eGggAQmQdh1jmT6D5LJXTonGvd/RP18OfDvU8/UvBmcrjSMwAzXXn610bgUx3xRgaI295OM1Luysd0W4uvgs3bMU9udwA3W2Z/GG+Kp9w2ODKZRzu1/9VW1wilzOAn19nqiOIDeYaPmAQfVdu5XyxJiGMj5LmVl79KWO/V0kxMMUq2lH9QCi1UxdVurFBjkYrqZBoKgKxG5e3SSFjo4z0e8h48aF97lMTUaJbwWdzvTqiICN+e4q4m5Vx3K2nP7Hl7TV7PCXOcP387atSx+Ocn70Rc2a8xeRo7fk4AF+6Lx/UlmwiVPJu8VM0Py1d2bcTK7NVpy2YHQIHiP/OkGU7laimF01KheapNR2tZ8Q5Nh7TLomqMMnfiBlizr0Q2g==
    DB_USERNAME: AgC8EjomUJfDzHPIkFGD/9k7Mw5vhlnbfTIlAbRTt307/RFxNcQp8Ler4dBxBGYj173uIqX3SGUnblj87qut8ARk12U9RVajaVU+QyZ9A75dIUOFHQWFy2SkKxuOj44dTAQZUyo7bcbVT3DeCYrj+D1Fhil2oedwYFaTN3fpuSVrnkVKVcGbR6SRqLb3RB3/gSEmLVDXF3TDpoQKigXXQsFZtu6fMCFGaGFQ2hvfl5aS3GEZl75Qp/euOR6qrB9hHVFgp0MvyK6iJFITYMscY2r8TkcJUYAnGszFK5BbkBHWjkBAtdN3pDMcuvrB6jbkA46Tap4v5IGdqXsdV25l2SSv0ObWSS6oUbOweW0K1yCZVgBMGbgbtXvMmDh14vN128jpJeTTLelfO6B1BIUi06/hx8j6l7Z5P3T+ym6EC6MxR/ZkOgz4gigfhEPr73A5hde4lT6H84u6yU7Dl0KPKwDEwjQgPOq6iT50cos4HzmqjqeT/NRaCmdd7JR+Gnl3xzSQp5aQYA9pwEhMBK+P6ciRtYxFAw4DAtxfskV3kV4QlC4omAD2d36fLA9g22G1JjIkWbT6nHBB+V/u+/nFjASDmvBbJkrr1QkmXRhPgalwmN0sJElH64TtlNS29bB+pj50Dm8TbZ1DfEShWgG3oaDh4kZ6H1UmIbFUaPstVE5CfdP9tafDlVGvMOy2tXWVurnLuTM2/sA=
  template:
    metadata:
      name: immich-postgres-credentials
      namespace: immich
