---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich.json: AgArw7bgxOy4pnWicZu4cj+vOiaG0G7TTRdEirNPfQoOHXDCGRs7ZPZJWQ3LmvmQPulTxnhHx5symtN0JkMCltPzX3OmbtFM/27JKcjotgAW2fLRhfttKN5gjSaMzyVOA4GRZCDoMu6xJ0TlW7uqjQlC+4XdLdyaFsDugjZU1UX130qQWKJ/Z9RC6QSzoEtrzVxn4YBCSFWgj6PGSWwlmWwJpNsef897DRw6Fvf9GhrO84cuE6xjU94iNZhgN4Glo9KS6soMHu2k3CnbhRCGL9o3wTKm/OUHQliNrRMBjMSuZ6UpgKIuwF+uWgDQKz7XMHKn3aAilxGrD6jtx5G6dWq1ifRhsICBT7jn+N12EmnsQ09e/gAgUNciO090uCdps2chbNDnWtZ047Yc9Zm0Zh/WSiOTRHO7rmCNNNsIpkNRgIuT660RZ6jMTI+JmeHrS3UdYS9orAehuka/gX+oDW1K/2OwGb/63z7B1UcQODsmsXy/QAPQ6oBsohMlJWy9eeMMSB3K0EnBEnnhKIF7TOhZYkYq0l35+/mStT0syXmKL4YV+dSVIyOu16vn3nPUFWGpHo0NJbl1URrtQ8EPKO6yewc4M65h3ykI89hLbUkjqNGWvFAp355rINg6N3nsEfrHx7isG8RQUPWyXFah1Tb8+zPzyHBMPvMR9rEOMUWnYW3aiie1DuJPQ9y+gZQz/05XhgDh6NPEHjDG5rwaDGEKLIj9tf72bN+YUi9InA7fezBc0BHIZtXU/M6ovnQuxgr1El3Ln1JiKQP2C2PDFqTRMdPqQCSofIaoD8HD5xkhKeNUt0pn6/HqVkHQX7oNGp5Rtm7Vsu51NGp2xZeEfJVdr+USrCu9al0si9LZFp9O+pC1nPJ5RU161QruYAixQYf/rsD7sMZSedlcxUpNBi2MuhbG+6l6RJc2LKThXY3hLpXVxXZ8n9HBgR8A5k2oCPFFBEvqDEYsth/VGCUmK1dGPd1aH+/Fw3sfYklGquJzjBXHQhbbsYy2gXxfKYf1XtKzBaMznPkYXaGxpFOQDnvtH1a5SfRtSEuRUCjoFcqESl0lnsihYYovv+kwvkeBmXu/eJBsxKfztTvk1os5mIwfav7rw9Ui86pQ2S4tiYX1QOGoiRsS5on2IeCc7cFpegIvrB2n4LJM0j/HYMEs3fFC73ThF1GvfixkTp803pYBCFDvTQ3jesiIT81SyNMJ49WxCpsD/ZrCjnFHw0Srw2SuhZ/pBJ5nLW3eO0cSbUUsPEOLhq5x4tTqk/PAoCIvhh7yKOsW8XdulKO7J5HhNWlwCdFQbPkg3oWHM2bd/rW9dIuIWKFcEnFzhjcGCv7hTZWTii3ThGCRH7ERURB7W1WSLcB4fpUJOi0=
  template:
    metadata:
      name: immich-config
      namespace: immich
