fullnameOverride: postgres-exporter-immich

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

config:
  datasource:
    host: immich-postgres.immich.svc.cluster.local
    port: "5432"
    database: immich
    sslmode: disable
    existingSecret: postgres-exporter-immich-dsn
